spring:
  redis:
    host: "127.0.0.1"
    password: "123456"
    port: 6379
    database: 0
    timeout: 30000
    lettuce:
      pool:
        max-active: 50
        max-idle: 30
        min-idle: 0
        max-wait: -1
    cache:
      redis:
        time-to-live: 3600000
        cache-null-values: false

  datasource:
    dynamic:
      hikari:
        connection-timeout: 10000
        connection-test-query: "SELECT 1"
        min-idle: 15
        max-pool-size: 15
        max-lifetime: 28000000
      primary: jie
      strict: false
      datasource:
          jie:
            username: "root"
            password: "123456"
            url: "jdbc:mysql://localhost:3306/jie?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true"
            driver-class-name: "com.mysql.cj.jdbc.Driver"
          jie2:
            username: "root"
            password: "123456"
            url: "jdbc:mysql://localhost:3306/jie2?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true"
            driver-class-name: "com.mysql.cj.jdbc.Driver"

server:
  undertow:
    io-threads: 4
    worker-threads: 32
    buffer-size: 1024
    direct-buffers: true
    accesslog:
      enabled: true
      prefix: ${spring.application.name}
      suffix: ".log"
      rotate: true
      dir: "/Users/hualala/data/logs"

#  tomcat:
#    uri-encoding: "UTF-8"
#    #最小线程数
#    min-spare-threads: 300
#    #最大线程数
#    max-threads: 8000
#    #最大链接数
#    max-connections: 10000
#    #最大等待队列长度
#    accept-count: 1000
  port: "6010"
#  connection-timeout: 20000
  error:
    whitelabel:
      enabled: "false"
    include-stacktrace: "ALWAYS"
  servlet:
    context-path: "/test/api/"

mybatis-plus:
  global-config:
    db-config:
      # 统一配置表名前缀
      table-prefix: t_
      id-type: auto
    banner: false
  mapper-locations: classpath*:mappers/*Mapper.xml
  typeAliasesPackage: com.example.test.entity

management:
  endpoints:
    web:
      exposure:
        include: '*'

rocketmq:
  accessKey: "a"
  secretKey: "b"
  nameSrvAddr: "c"
  topic: workflow_testb
  groupId: GID-test1
  tag: mq_shop_settle_in_tag11
  orderTopic: recycle_order
  orderGroupId: GID-test
  orderTag: recycle_order_001

#### feign
#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 9000

#ribbon的超时时间
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  recycl-rabbish-service:
    name: recycl-rabbish
## feign end

merber:
  name: 订单服务中的配置名称
  age: 18
