spring:
  redis:
    host: "127.0.0.1"
    password: "123456"
    port: 6379
    database: 0
    timeout: 5000
    lettuce:
      pool:
        max-active: 30
        max-idle: 30
        min-idle: 0
    cache:
      redis:
        time-to-live: 3600000
        cache-null-values: false

  datasource:
    connectionTestQuery: "SELECT 1"
    connectionTimeout: "10000"
    url: "jdbc:mysql://localhost:3306/jie?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true"
    minimumIdle: "15"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    maximumPoolSize: "15"
    password: "123456"
    username: "root"
    maxLifetime: "28770000"
    hikari:
      minimum-idle: "9"
      maximum-pool-size: "80"
      max-lifetime: "28000000"
      connection-test-query: "SELECT 1"

server:
  tomcat:
    max-threads: "1000"
    uri-encoding: "UTF-8"
  port: "6010"
  error:
    whitelabel:
      enabled: "false"
    include-stacktrace: "ALWAYS"
  servlet:
    context-path: "/test/api/"

mybatis-plus:
  global-config:
    db-config:
      # 统一配置表名前缀
      table-prefix: t_
      id-type: auto
    banner: false
  mapper-locations: classpath*:mappers/*Mapper.xml
  typeAliasesPackage: com.example.test.entity

management:
  endpoints:
    web:
      exposure:
        include: '*'

rocketmq:
  accessKey: "a"
  secretKey: "b"
  nameSrvAddr: "c"
  topic: workflow_testb
  groupId: GID-test1
  tag: mq_shop_settle_in_tag11
  orderTopic: recycle_order
  orderGroupId: GID-test
  orderTag: recycle_order_001

#### feign
#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 9000

#ribbon的超时时间
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  recycl-rabbish-service:
    name: recycl-rabbish
## feign end

merber:
  name: 订单服务中的配置名称
  age: 18
