spring:
  redis:
    host: "redis.testb.ttjianbao.com"
    password: "yjkj305-live-cache-test"
    port: 6379
    database: 0
  datasource:
    connectionTestQuery: "SELECT 1"
    connectionTimeout: "10000"
    url: "jdbc:mysql://rm-2zeefmb98v6f5qeuf.mysql.rds.aliyuncs.com:3306/ttjb-testb?relaxAutoCommit=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf8&useSSL=false"
    minimumIdle: "15"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    maximumPoolSize: "15"
    password: "yjkj305!@#-db-test"
    username: "ttjb"
    maxLifetime: "28770000"
    hikari:
      minimum-idle: "9"
      maximum-pool-size: "80"
      max-lifetime: "28000000"
      connection-test-query: "SELECT 1"

server:
  tomcat:
    max-threads: "1000"
    uri-encoding: "UTF-8"
  port: "6011"
  error:
    whitelabel:
      enabled: "false"
    include-stacktrace: "ALWAYS"
  servlet:
    context-path: "/test/api/"

mybatis-plus:
  global-config:
    db-config:
      # 统一配置表名前缀
      table-prefix: t_
      id-type: auto
    banner: false
  mapper-locations: classpath*:mappers/*Mapper.xml
  typeAliasesPackage: com.example.test.entity

management:
  endpoints:
    web:
      exposure:
        include: '*'

#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 50000
#        readTimeout: 5000
#  recycl-rabbish-service:
#    name: recycl-rabbish

merber:
  name: 订单服务中的配置名称
  age: 18
