package com.example.test.entity.po;

import com.baomidou.mybatisplus.annotation.TableName;
import io.swagger.annotations.ApiModel;
import lombok.Data;
import lombok.EqualsAndHashCode;

import java.io.Serializable;
import java.util.Date;

@Data
@EqualsAndHashCode(callSuper = false)
@TableName("tbl_dashboard_copy_index")
@ApiModel(value="仪表盘对象", description="仪表盘")
public class TblDashboardCopyIndex implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dashboard_copy_index.id
     *
     * @mbg.generated Wed Sep 08 11:11:33 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dashboard_copy_index.parent_id
     *
     * @mbg.generated Wed Sep 08 11:11:33 CST 2021
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dashboard_copy_index.db_id
     *
     * @mbg.generated Wed Sep 08 11:11:33 CST 2021
     */
    private Long dbId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dashboard_copy_index.source_db_id
     *
     * @mbg.generated Wed Sep 08 11:11:33 CST 2021
     */
    private Long sourceDbId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dashboard_copy_index.create_time
     *
     * @mbg.generated Wed Sep 08 11:11:33 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dashboard_copy_index.update_time
     *
     * @mbg.generated Wed Sep 08 11:11:33 CST 2021
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dashboard_copy_index.is_del
     *
     * @mbg.generated Wed Sep 08 11:11:33 CST 2021
     */
    private Byte isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_dashboard_copy_index
     *
     * @mbg.generated Wed Sep 08 11:11:33 CST 2021
     */
    private static final long serialVersionUID = 1L;

}